import Head from 'next/head'
import Link from 'next/link';
import Footer from '../../components/Footer';
import Header from '../../components/Header';
import styles from '../../styles/Newsletters.module.css';
import axios from 'axios';

const Newsletters = ({ post }) => {

    const postList = post?.docs
    
  return (
    <div className={styles.newletters}>
        <Head>
            <title>XRAtlas</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/xr.jpeg" />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true'/>
        </Head>
        <main className={styles.main}>
            <div className={styles.star_bg}></div>
            <div className={styles.container}>
                <Header />
                <div className={styles.main_content}>
                    <div className={styles.heading}>
                        <h2>Newsletters</h2>
                        <p>Welcome to the XRAtlas Newsletter, where we keep you up to date on the latest news, insights, and events in the world of virtual and augmented reality, and other emerging technologies that are shaping the future of the metaverse. From industry updates and cutting-edge innovations to fascinating applications and inspiring stories, we bring you a curated selection of the most relevant and interesting developments in the metaverse. Subscribe now and stay ahead of the curve in the exciting realm of the metaverse.</p>
                    </div>
                    <div className={styles.wrapper}>
                        <div className={styles.list}>
                            {
                                postList && postList.map(({_id, postTags, postAuthor, postUrl, postContent, postName, postLength}) => {
                                    return(
                                        <Link href={`/newletters/${_id}`} key={_id}>
                                            <div className={styles.newsletter}>
                                                <div className={styles.content}>
                                                    <div className={styles.text}>
                                                        <h3>{postName}</h3>
                                                        <p>{`${postContent.substr(0, 280)}...`}</p>
                                                    </div>
                                                    <div className={styles.author}>
                                                        <img src="/AVATAR.svg" alt="" />
                                                        <p>{postAuthor}<span> · {`${postLength} min read`}</span></p>
                                                    </div>
                                                </div>
                                                <div className={styles.photo}>
                                                    <img src={postUrl} width={140} height={140} alt=""/>
                                                </div>
                                            </div>
                                        </Link>
                                    )
                                })
                            }
                            <div className={styles.pagination}>
                                <span>1</span>
                                <span>2</span>
                                <span>3</span>
                            </div>
                            
                        </div>
                    </div>  
                </div>
                <Footer />
                
            </div>
        </main>
    </div>
  )
}

export default Newsletters;


export async function getStaticProps(){

    const options = {
        method : "GET",
        url : "https://xr-speeds-production.up.railway.app/pagination",
        params : {
            page : 1,
            limit : 3
        }
    }
    try {
        const data = await axios.request(options)
        const result = data.data; 
        return { 
            props : { post : result }
         }
         
      } catch (error) {
          console.log(error)
      }
}