export const WYSIWYG_EDITOR_DEFAULT_SETTINGS = {
    /*Some of the values are assigned within TextEditor.tsx*/

    webDriverTestID: undefined,
    onChange: undefined,
    onEditorStateChange: undefined,
    onContentStateChange: undefined,
    initialContentState: undefined,
    defaultContentState: undefined,
    contentState: undefined,
    editorState: undefined,
    defaultEditorState: undefined,
    toolbarOnFocus: undefined,
    spellCheck: undefined,
    stripPastedStyles: undefined,
    toolbar: undefined,
    toolbarCustomButtons: undefined,
    toolbarClassName: undefined,
    toolbarHidden: undefined,
    locale: undefined,
    localization: undefined,
    editorClassName: 'input', // notice the class name is input, referring to bulma's input class
    wrapperClassName: 'field',// notice the class name is field, referring to bulma's field class
    toolbarStyle: undefined,
    editorStyle: undefined,
    wrapperStyle: undefined,
    uploadCallback: undefined,
    onFocus: undefined,
    onBlur: undefined,
    onTab: undefined,
    mention: undefined,
    hashtag: undefined,
    textAlignment: undefined,
    readOnly: undefined,
    tabIndex: undefined,
    placeholder: undefined,
    ariaLabel: undefined,
    ariaOwneeID: undefined,
    ariaActiveDescendantID: undefined,
    ariaAutoComplete: undefined,
    ariaDescribedBy: undefined,
    ariaExpanded: undefined,
    ariaHasPopup: undefined,
    customBlockRenderFunc: undefined,
    wrapperId: undefined,
    customDecorators: undefined,
    editorRef: undefined,
    handleKeyCommand: undefined,
    handlePastedText: undefined,
    customStyleMap: undefined,
}