import React from 'react'
import Head from 'next/head'
import Header from '../../components/Header'
import styles from '../../styles/Create.module.css'
import Image from 'next/image'
import { Container, HStack, Text } from '@chakra-ui/react'
import dynamic from 'next/dynamic'
import 'react-markdown-editor-lite/lib/index.css';
import MarkdownIt from 'markdown-it';

const MdEditor = dynamic(() => import('react-markdown-editor-lite'), {
    ssr: false,
});


const Create = () => {

    const mdParser = new MarkdownIt(/* Markdown-it options */);
    function handleEditorChange({ html, text }) {
        console.log('handleEditorChange', html, text);
    }
  return (
    <div className={styles.create}>
        <Head>
            <title>XRAtlas</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/xr.jpeg" />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true'/>
        </Head> 
        <main>
            <Header />
            <Container maxW="900px" mt="8">
                <HStack justifyContent="flex-end">
                    <button className={styles.publish_btn}>
                        <Image src="/upload.svg" width="14" height="14" alt=""/>
                        Publish
                    </button>
                </HStack>
                <Text color="whiteAlpha.500" as="h1" fontSize="2xl">Title</Text>
                <MdEditor 
                    style={{ height: '500px' }}
                    renderHTML={text => mdParser.render(text)} 
                    onChange={handleEditorChange}
                />
            </Container>
        </main>
    </div>
  )
}

export default Create;