import React from 'react'
import Header from '../../components/Header'
import Head from 'next/head'
import { Grid, GridItem, Container, Box, VStack, Text, Heading, HStack, Button } from '@chakra-ui/react'
import styles from '../../styles/user.module.css'
import Image from 'next/image'

const user = () => {
  return (
    <div className={styles.user}>
        <Head>
            <title>XRAtlas</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/xr.jpeg" />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true'/>
        </Head> 
        <main>
            <Header />
            <Container maxW="1200px">
                <div className="">
                    <h2>PROFILE</h2>
                    <div>
                    <Grid gridTemplateColumns={'310px 1fr 310px'} gap={2}>
                        <GridItem border="1px" borderColor="whiteAlpha.500" borderRadius="3xl" p={3}>
                            <Text mt="4">Summary</Text>
                            <Text>Lorem ipsum dolor sit amet consectetur. Blandit facilisi ut leo ut in venenatis. Semper morbi eu aliquam at eu vestibulum gravida nibh. Nec dictum feugiat ut pharetra odio.</Text>
                            <Box marginTop="14rem">
                                <Text mt="4" color="whiteAlpha.600">Connect with me</Text>
                                <Box mt="4" justifyContent="left" textAlign="left">
                                    <Box display="flex" gap="2" mb="4" justifyContent="flex-start">
                                        <Image src="/Vector (13).svg" width="14" height="14" alt="" />
                                        <Text fontSize="14px" ml="2">Mufasa Mufasa</Text>
                                    </Box>
                                    <Box display="flex" gap="2" mb="4">
                                        <Image src="/Vector (14).svg" width="14" height="14" alt="" />
                                        <Text fontSize="14px" ml="2">Mufasa Mufasa</Text>
                                    </Box>
                                    <Box display="flex" gap="2" mb="4">
                                        <Image src="/Vector (15).svg" width="14" height="14" alt="" />
                                        <Text fontSize="14px" ml="2">Mufasa Mufasa</Text>
                                    </Box>
                                    <Box display="flex" gap="2" mb="4">
                                        <Image src="/Vector (16).svg" width="14" height="14" alt="" />
                                        <Text fontSize="14px" ml="2">Mufasa Mufasa</Text>
                                    </Box>
                                </Box>
                            </Box>
                        </GridItem>
                        <GridItem p={3}>
                            <Image src="/image 1.svg" width="100" height="340" alt="" className={styles.profile_image} />
                            <Box border="1px" borderColor="whiteAlpha.500" borderRadius="3xl" p={3} mt="3">
                                <HStack justifyContent="space-between">
                                    <Button background="#F40580" color="white" borderRadius="full">
                                        <Image src="/medal.svg" width="16" height="16" alt=""  style={{marginRight : "10px"}}/> 
                                        Contributor
                                    </Button>
                                    <Button 
                                    // variant="unstyled"
                                    // __css={{
                                    //     color :"white",
                                    //     border : "1px solid white",
                                    //     padding : "2px",
                                    //     width : "120px",
                                    //     display : "flex",
                                    //     // border: "1px solid linear-gradient(#FB047B 100%, #130EFF 99.88%)",
                                    //     background : "transparent",
                                    //     borderRadius : "25px"
                                    // }}
                                    borderRadius="full" 
                                    color="white" 
                                    border="1px" 
                                    borderColor=""
                                    background="transparent"
                                    >
                                        <Image src="/edit.svg" width="16" height="16" alt="" style={{marginRight : "10px"}}/> 
                                        Edit
                                    </Button>
                                </HStack>
                                <Box mt="8" pb="6" borderTop="1px" borderColor="whiteAlpha.500">
                                    <HStack mt="3">
                                        <HStack flex="0.5">
                                            <Image src="/medal.svg" width="16" height="16" alt=""  style={{marginRight : "10px"}}/> 
                                            <Box>
                                                <Text>Name</Text>
                                                <Text>Mufasa Mufasa</Text>
                                            </Box>
                                        </HStack>
                                        <HStack flex="0.5">
                                            <Image src="/medal.svg" width="16" height="16" alt=""  style={{marginRight : "10px"}}/> 
                                            <Box>
                                                <Text>Display Name </Text>
                                                <Text>A.Aot</Text>
                                            </Box>
                                        </HStack>
                                    </HStack>
                                    <HStack mt="6">
                                        <HStack flex="0.5">
                                            <Image src="/medal.svg" width="16" height="16" alt=""  style={{marginRight : "10px"}}/> 
                                            <Box>
                                                <Text>Email address</Text>
                                                <Text>Hello@carrotlabs.co</Text>
                                            </Box>
                                        </HStack>
                                        <HStack flex="0.5">
                                            <Image src="/medal.svg" width="16" height="16" alt=""  style={{marginRight : "10px"}}/> 
                                            <Box>
                                                <Text>Phone number</Text>
                                                <Text>(+84) 399 999 999</Text>
                                            </Box>
                                        </HStack>
                                    </HStack>
                                    <HStack mt="6">
                                        <HStack flex="0.5">
                                            <Image src="/medal.svg" width="16" height="16" alt=""  style={{marginRight : "10px"}}/> 
                                            <Box>
                                                <Text>website</Text>
                                                <Text>Hello@carrotlabs.co</Text>
                                            </Box>
                                        </HStack>
                                        
                                    </HStack>
                                </Box>
                            </Box>
                        </GridItem>
                        <GridItem  h='10' bg='papayawhip' />
                    </Grid>
                    </div>
                </div>
            </Container>
        </main>
    </div>
  )
}

export default user