import Head from 'next/head'
import Link from 'next/link'
import { useEffect } from 'react'
import Community from '../components/Community'
import Footer from '../components/Footer'
import Glimpse from '../components/Glimpse'
import Hero from '../components/Hero'
import Information from '../components/Information'
// import Mission from '../components/Mission'
import RecentNewsletter from '../components/RecentNewsletter'
import RecentPodcast from '../components/RecentPodcast'
// import Subscribe from '../components/Subscribe'
import styles from '../styles/Home.module.css'

const data = {
  title : "Recent Newsletters",
}

export default function Home() {

  useEffect(() => {
    const fetching = async () => {
      await fetch('http://localhost:3000/api/hello').then(res => res.json()).then(data => console.log(data))
    }

    fetching()
  },[])

  return (
      <div className={styles.container}>
        <Head>
          <title>XRAtlas</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/xr.jpeg" />
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true'/>
        </Head>

        <main className={styles.main} id="top">
          <Hero />
          <Information />
          <RecentPodcast />
          <Glimpse />
          <RecentNewsletter data={data}/>
          <Community />
          <Footer />
        </main>
      </div>
  )
}
